# Generated by Django 5.2.6 on 2025-11-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_embedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
