# Generated by Django 5.2.6 on 2025-11-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookinteraction',
            name='status',
            field=models.CharField(blank=True, choices=[('WR', 'Will Read'), ('RDG', 'Reading'), ('RD', 'Read')], max_length=4, null=True),
        ),
    ]
